@startuml
left to right direction

package "core" {
  package "apis" {
    interface EmployeesApi
    interface CancelApi
    interface PaymentsApi
    interface ProposalApi
    interface TimeHoldersApi
  }

  interface Repository<E extends Entity>
  interface Messenger
}

package "bl" {
  class EmployeesService {
    - employees : Repository<Employee>
  }
  class CancelService {
    - repository : Repository<Approved>
    - messenger : Messenger
  }
  class PaymentsService {
    - payments: Repository<Payments>
    - messenger : Messenger
  }
  class ProposalService {
    - proposals : Repository<Proposal>
    - messenger : Messenger
    - timeHoldersApi : TimeHoldersApi
    - paymentsApi : PaymentsApi
  }
  class TimeHoldersService {
    - ths: Repository<TimeHolder>
    - messenger : Messenger
  }
}

EmployeesService ..|> EmployeesApi
CancelService ..|> CancelApi
TimeHoldersService ..|> TimeHoldersApi
ProposalService ..|> ProposalApi
PaymentsService ..|> PaymentsApi

EmployeesService ..> Repository
CancelService ..> Repository
ProposalService ..> Repository
PaymentsService ..> Repository
TimeHoldersService ..> Repository

CancelService ..> Messenger
ProposalService ..> Messenger
PaymentsService ..> Messenger
TimeHoldersService ..> Messenger

ProposalService ..> TimeHoldersApi
ProposalService ..> PaymentsApi

@enduml