@startuml
'left to right direction

class Employee {
  name : String
}


class Manager {
}

class Paymaster {
}

class Worker {
}

class Proposal {
  when : long
  pending : boolean
}

class ScheduledItem {
  when : long
}

class Payment {
  amount : long
}

class TimeHolder {
  duration : long  
}

hide class circle

Payment -up-|> ScheduledItem
TimeHolder -up-|> ScheduledItem
Worker -down-|> Employee
Paymaster -left-|> Employee

Proposal "1" -right-> "1" ScheduledItem
Employee "*" --> "0..1" Manager
Employee "*" --> "1" Paymaster
ScheduledItem "*" -right-> "1" Employee : "owned by >"
ScheduledItem "*" -right-> "1" Employee : "scheduled for >"

Manager -up-|> Employee

@enduml